name: Build and Push Docker Image

# This workflow now runs on two triggers:
# 1. When you push a tag that starts with 'v' (like v1.0.0, v1.0.1)
# 2. When you want to run it manually from the Actions tab (workflow_dispatch)
on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to push to GHCR

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get lowercase owner name
      id: owner_lowercase
      run: echo "name=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

    # This action automatically extracts metadata and figures out the tags
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ steps.owner_lowercase.outputs.name }}/currency-converter
        # This tells the action to create two tags:
        # 1. The Git tag (e.g., v1.0.1)
        # 2. The 'latest' tag
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern=latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        # This line is changed to use the tags from the 'meta' step
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        
        # --- THIS IS THE NEW LINE YOU NEED ---
        # This securely passes your secret to the 'ARG API_KEY' in your Dockerfile
        build-args: |
          API_KEY=${{ secrets.API_KEY }}
